#!/usr/bin/env python3
"""Кадры гипсового макета → файлы сайта.

Берёт папку сырых рендеров tools/model-render.py — по подпапке на плиту
(<плита>/meta.json + PNG) — и пишет:
  media/model/seq/<плита>/<ширина>/fNNN.webp   кадры раскладки для прокрутки;
  media/model/final-<плита>-<ширина>.{webp,avif} финальный кадр без света в квартирах;
  media/model/final-lit-<плита>-<ширина>.{webp,avif} он же со светом — для страницы без JS;
  media/model/light-<id>-<ширина>.webp   свет квартиры: прибавка к финальному
                                         кадру своей плиты (на сайте — «lighter»);
  media/model/close-<id>-<ширина>.{webp,avif} крупный план квартиры;
  js/model-data.js                     плиты (этажи, размеры, подписи этажей по
                                         кадрам, контуры квартир), подписи комнат.

  python3 tools/model-pack.py /путь/к/сырым/рендерам
"""
import glob
import json
import os
import re
import sys

import numpy as np
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'media/model')
JS = os.path.join(ROOT, 'js/model-data.js')
PLANS = os.path.join(ROOT, 'js/plans-data.js')
STAMP = '2026-10-01T00:00:00.000Z'
ORIGIN = ('Origin: rendered in Blender (Cycles) by tools/model-render.py from the typical-floor key plans '
          'in media/plans/src/*.pdf (vector drawings extracted by tools/model-floor.py); furniture placed after '
          'the 3D views in the same sheets; not generated by Impeccable.')


def prov(fn):
    with open(fn + '.json', 'w', encoding='utf-8') as fh:
        json.dump({'prompt': ORIGIN, 'createdAt': STAMP}, fh, ensure_ascii=False, indent=2)
        fh.write('\n')


def load8(path):
    """PNG 8/16 бит → RGB uint8 (рендер уже в цветовом пространстве экрана)."""
    im = Image.open(path)
    a = np.asarray(im)
    if a.dtype == np.uint16:
        a = (a / 257.0 + 0.5).astype(np.uint8)
    return Image.fromarray(a[..., :3] if a.ndim == 3 else a).convert('RGB')


BG = np.array([18, 20, 22], np.float32) / 255     # --room: графит витрины


def lift(im, e=0.045):
    """Чёрный фон рендера → графит страницы. Мягкий максимум с цветом фона:
    тени темнее графита поднимаются до него, всё, что светлее, не меняется —
    кадр без шва переходит в фон секции. Белое остаётся белым."""
    x = np.asarray(im).astype(np.float32) / 255
    sm = lambda v: (v + BG + np.sqrt((v - BG) ** 2 + e * e)) / 2
    y = sm(x) - (sm(np.zeros(3, np.float32)) - BG) * (1 - x)
    return Image.fromarray(np.clip(y * 255 + 0.5, 0, 255).astype(np.uint8))


def edges(im):
    """Края кадра гаснут в графит (10% по бокам, 7% сверху, 4% снизу):
    кадр без рамки встаёт в фон секции. Запечено в картинку — маска CSS
    на холсте стоила бы перерисовки на каждом кадре прокрутки."""
    a = np.asarray(im).astype(np.float32)
    h, w = a.shape[:2]
    sm = lambda t: (lambda c: c * c * (3 - 2 * c))(np.clip(t, 0, 1))
    x, y = (np.arange(w) + 0.5) / w, (np.arange(h) + 0.5) / h
    m = (np.minimum(sm(x / 0.10), sm((1 - x) / 0.10))[None, :] *
         np.minimum(sm(y / 0.07), sm((1 - y) / 0.04))[:, None])[..., None]
    return Image.fromarray(np.clip(a * m + BG * 255 * (1 - m) + 0.5, 0, 255).astype(np.uint8))


def save(im, base, w, q=74, avif=False):
    if im.width != w:
        im = im.resize((w, round(im.height * w / im.width)), Image.LANCZOS)
    im.save(base + '.webp', 'WEBP', quality=q, method=6)
    prov(base + '.webp')
    if avif:
        im.save(base + '.avif', 'AVIF', quality=q - 14)
        prov(base + '.avif')
    return im.size


def frame_close(im, rooms, margin=0.06, gain=1.3):
    """Крупный план, где квартира мелкая в кадре (Б-2 огибает торец дома),
    кадрируем по её свету — тёплые пиксели, соседи нейтрально-серые — с
    полями, сохраняя 4:3; номера комнат пересчитываем."""
    a = np.asarray(im).astype(np.int16)
    H, W = a.shape[:2]
    ys, xs = np.nonzero(a[..., 0] - a[..., 2] > 16)
    if len(xs) < 1000:
        return im, rooms
    x0, x1 = np.percentile(xs, [1, 99]) / W - margin + np.array([0, 2 * margin])
    y0, y1 = np.percentile(ys, [1, 99]) / H - margin + np.array([0, 2 * margin])
    w, h = (x1 - x0) * W, (y1 - y0) * H
    w, h = (h * 4 / 3, h) if w / h < 4 / 3 else (w, w * 3 / 4)
    if W / w < gain:
        return im, rooms
    left = min(max((x0 + x1) / 2 * W - w / 2, 0), W - w)
    top = min(max((y0 + y1) / 2 * H - h / 2, 0), H - h)
    box = (round(left), round(top), round(left + w), round(top + h))
    out = [dict(r, at=[round((r['at'][0] * W - box[0]) / (box[2] - box[0]), 4),
                       round((r['at'][1] * H - box[1]) / (box[3] - box[1]), 4)]) for r in rooms]
    return im.crop(box), out


def plan_items():
    src = open(PLANS, encoding='utf-8').read()
    data = json.loads(src[src.index('{'):src.rindex(';')])
    return {p['id']: p for p in data['list']}


def numbers(plan, rooms):
    """Номера помещений — как в экспликации листа: по названию, а одноимённые
    (два санузла, две спальни) — по площади: большая комната макета получает
    номер большего помещения листа."""
    out = [None] * len(rooms)
    for name in {r['name'] for r in rooms}:
        mine = sorted((i for i, r in enumerate(rooms) if r['name'] == name), key=lambda i: rooms[i].get('area', 0))
        theirs = sorted((it for it in plan.get('items', []) if it['name'] == name), key=lambda it: it['area'])
        if len(mine) == len(theirs):
            for i, it in zip(mine, theirs):
                out[i] = it['n']
        else:                                   # число не сошлось — по порядку, как в листе
            for i, it in zip(sorted(mine), sorted(theirs, key=lambda it: it['n'])):
                out[i] = it['n']
    return out


def pack_plate(raw, items, close):
    """Одна плита: кадры раскладки, финал со светом квартир, крупные планы."""
    meta = json.load(open(os.path.join(raw, 'meta.json'), encoding='utf-8'))
    key = meta['plate']['key']
    plate = {'label': meta['plate']['label'], 'floors': meta['plate']['floors']}

    if 'seq' in meta:
        sq = meta['seq']
        frames = sorted(glob.glob(os.path.join(raw, 'seq', 'f*.png')))
        widths = [w for w in (1440, 960) if w <= sq['w']] or [sq['w']]
        for w in widths:
            d = os.path.join(OUT, 'seq', key, str(w))
            os.makedirs(d, exist_ok=True)
            for f in frames:
                save(edges(lift(load8(f))), os.path.join(d, os.path.basename(f)[:-4]), w, q=70)
        plate['seq'] = {'n': len(frames), 'w': sq['w'], 'h': sq['h'], 'widths': widths, 'src': 'media/model/seq/%s/' % key,
                        'floors': sq['floors'], 'anchors': sq['anchors'][:len(frames)]}

    if 'final' in meta:
        fm = meta['final']
        base8 = edges(lift(load8(os.path.join(raw, 'base0001.png'))))
        widths = [w for w in (1920, 1280, 960) if w <= base8.width] or [base8.width]
        for w in widths:
            save(base8, os.path.join(OUT, 'final-%s-%d' % (key, w)), w, q=78, avif=True)
        b = np.asarray(base8).astype(np.int16)
        layers, diffs = {}, []
        for path in sorted(glob.glob(os.path.join(raw, 'lit_*0001.png'))):
            fid = re.match(r'lit_(\w+?)0001\.png', os.path.basename(path)).group(1)
            lit = np.asarray(edges(lift(load8(path)))).astype(np.int16)
            d = np.clip(lit - b, 0, 255)
            diffs.append(d)
            diff = Image.fromarray(d.astype(np.uint8))
            for w in widths:
                save(diff, os.path.join(OUT, 'light-%s-%d' % (fid, w)), w, q=82)
            layers[fid] = 'media/model/light-%s-' % fid
        # картинка для страницы без JS: финальный кадр со светом во всех квартирах
        if diffs:
            lit_all = Image.fromarray(np.clip(b + sum(diffs), 0, 255).astype(np.uint8))
            for w in widths:
                save(lit_all, os.path.join(OUT, 'final-lit-%s-%d' % (key, w)), w, q=78, avif=True)
        plate['final'] = {'w': fm['w'], 'h': fm['h'], 'widths': widths, 'base': 'media/model/final-%s-' % key,
                          'layers': layers, 'flats': fm['flats']}

    for fid, cm in meta.get('close', {}).items():
        path = os.path.join(raw, 'close-%s.png' % fid)
        if not os.path.exists(path):
            continue
        im, cm_rooms = frame_close(load8(path), cm['rooms'])
        widths = [w for w in (1600, 960) if w <= im.width] or [im.width]
        if im.width < 1600 and im.width not in widths:
            widths.insert(0, im.width)
        for w in widths:
            save(im, os.path.join(OUT, 'close-%s-%d' % (fid, w)), w, q=78, avif=True)
        ns = numbers(items.get(fid, {}), cm_rooms)
        rooms = [{'n': n, 'name': r['name'], 'x': r['at'][0], 'y': r['at'][1]} for n, r in zip(ns, cm_rooms)]
        close[fid] = {'w': im.width, 'h': im.height, 'widths': widths, 'src': 'media/model/close-%s-' % fid, 'rooms': rooms}
    return key, plate


def main(raw):
    os.makedirs(OUT, exist_ok=True)
    items = plan_items()
    plates, close = {}, {}
    for m in sorted(glob.glob(os.path.join(raw, '*', 'meta.json'))):
        key, plate = pack_plate(os.path.dirname(m), items, close)
        plates[key] = plate
        print(key, '· seq', plate.get('seq', {}).get('n'), '· final layers', len(plate.get('final', {}).get('layers', {})))
    if not plates:
        sys.exit('нет <плита>/meta.json в ' + raw)
    data = {'plates': plates, 'close': dict(sorted(close.items()))}
    with open(JS, 'w', encoding='utf-8') as fh:
        fh.write('/* Сгенерировано tools/model-pack.py — не править вручную.\n'
                 '   Гипсовый макет типовых этажей: по плите на этаж из листов (кадры\n'
                 '   раскладки, финальный кадр со светом квартир), крупные планы\n'
                 '   квартир. Координаты — доли кадра. */\n')
        fh.write('window.MK_MODEL = ' + json.dumps(data, ensure_ascii=False, separators=(',', ':')) + ';\n')
    print('plates', len(plates), '· close', len(close))


if __name__ == '__main__':
    main(os.path.abspath(sys.argv[1]))
